# Generated by Django 5.2.9 on 2026-04-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sustainability_preference',
        ),
    ]
