# Generated by Django 5.2.9 on 2026-04-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sustainability_score',
        ),
    ]
